// SesliTab — Vite entry point.
// Imports the main app module, package UI controllers, discovery UI, app shell, and styles.

import './src/style.css'
import './src/discovery.css'
import './src/package8TeacherUi.css'
import './src/stageATeacherPresentation.css'
import './src/package11TunerUi.css'
import './src/appShell.css'
import './src/mobileReviewUi.css'
import './src/app.js'
import './src/package3Ui.js'
import './src/stageCNoteSelectionUi.js'
import './src/package4Ui.js'
import './src/package5Ui.js'
import './src/package7Ui.js'
import './src/discoveryUi.js'
import './src/package8TeacherUi.js'
import './src/stageATeacherPresentation.js'
import './src/scoreViewUi.js'
import './src/package11TunerUi.js'
import './src/appShell.js'
import './src/reviewInspectorUi.js'
